dataset_name: 'covid_point'
window: 14

adj_threshold: 0.1

detrend: False
scale: True
scaling_axis: 'global'  # ['channels', 'global']
scaled_target: True

epochs: 3000
samples_per_epoch: 240
#batch_size: 32
batch_size: 16
patience: 2000
aggregate_by: ['mean']

model_name: 'rectsi'
pred_loss_weight: 1

d_hidden: 64
d_emb: 16
d_ff: 64
ff_dropout: 0
kernel_size: 2
