dataset_name: 'pems_point'
subdataset_name: 'PEMS07'
window: 24

adj_threshold: 0.1

detrend: False
scale: True
scaling_axis: 'global'  # ['channels', 'global']
scaled_target: True

epochs: 500
#samples_per_epoch: 9600  # 160 batch of 32
batch_size: 128
aggregate_by: ['mean']

model_name: 'rectsi'
pred_loss_weight: 1

d_hidden: 64
d_emb: 16
d_ff: 64
ff_dropout: 0
kernel_size: 2
